version: "3.8"
services:
    certbot:
        image: certbot/dns-cloudflare-docker
        build: .
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/etc/letsencrypt:/etc/letsencrypt"
            - "/var/lib/letsencrypt:/var/lib/letsencrypt"
            - "~/.secrets:/secrets"
